name: Storybook preview on PR

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Check the files and build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: |
          npm ci

      - name: Check types & codestyle
        run: |
          npx tsc
          npm run lint

      - name: Build components & storybook
        run: |
          npm run build:components
          npm run build:storybook

  deploy:
    name: Deploy preview
    runs-on: self-hosted
    if: github.event.pull_request.draft == false
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: |
          npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
          exitZeroOnChanges: true
          exitOnceUploaded: true
          buildScriptName: "build:storybook"
