name: Release the components on NPM

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  publish_release:
    name: Build & Publish components to NPM
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: |
          npm ci

      - name: Build components
        run: |
          npm run build:components
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
